#+hugo_base_dir: ../
#+hugo_section: posts

#+hugo_auto_set_lastmod: f

#+date: 2020-06-05T11:31:24-04:00
#+hugo_categories: tech
#+hugo_tags: Linux coding tools vm 100DaysToOffload

#+hugo_draft: true

#+title: How I use Linux desktop at work - Part2 - Windown manager and GUI

Part 2 of the series /How I use Linux desktop at work/

Just to recap, this series is describing how I leverage vagrant and virtualbox to provision development VM on my work PCs. I'm also taking the opportunity to build them from scratch with the tools I use at home.

In the post, we go over:
1. creating a basic arch VM
2. configure memory/cpu and disk allocation
3. install X related packages
4. Install one Window Manager (TBD: Mate?, xfce?, Cinnamon? )

* Creating the basic arch VM

This will be an arch based vagrant VM, and I'll use the official arch vagrant box:

#+BEGIN_SRC bash
mkdir devbox-arch
cd devbox-arch
vagrant init archlinux/archlinux
#+END_SRC

That's it. Lets try it:

#+BEGIN_SRC bash
vagrant up
vagrant ssh
uname -a
#+END_SRC

* configure memory/cpu and disk allocation

This is good enough for console, but if we are going to use this for a development VM running X, we need to allocate more resources, setup graphic properties, setup host/guest integration.

here is what the vagrant file looks like now:

#+BEGIN_SRC ruby :file Vagrantfile
TODO=123
#+END_SRC

* Footnotes
# needed to get a proper formatted summary in index page and rss
# <!--more-->
